version: "3.9"

services:
  kali:
    container_name: kali
        build:
            context: .
            dockerfile: Dockerfile
    environment:
      - NGROK_TOKEN=${NGROK_TOKEN}
    ports:
      - 8080:8080
    restart: unless-stopped
